name: Test

on:
  push: 
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Update pakages
      run: sudo apt update
    - name: Exe_file
      run: python main.py
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: version 1
    
  
