name: Test

on:
  push: 
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Update pakages
      run: sudo apt update
    - name: Streamlit App Action
      run: pip install streamlit
    - name: Exe_file
      run: streamlit run main.py
    - name: Get url
      run: start http://74.249.13.142:8501/
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: version 1
    
  
