name: Test

on:
  push: 
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Update pakages
      run: sudo apt update
    - name: Streamlit App Action
      uses: streamlit/streamlit-app-action@v0.0.3
      with:
        app-path: streamlit run main.py
        pytest-args: -v
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: version 1
    
  
