name: Test

on:
  push: 
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Update pakages
      run: sudo apt update
    - name: Streamlit App Action
      run: pip install streamlit
    - name: Execution du fichier
      run: streamlit run main.py
    - name: get url
      run: curl http://10.1.0.137:8501/
        if:{{ Always}}
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: version 1
    
  
